### ISSUE TITLE
Task list of relase v0.7.0

### ISSUE THREAD

**Issue by ruimashita** [blue-oil/blueoil#279]
Task list of release.

* [x] Write release note as draft: https://github.com/blue-oil/blueoil/releases/tag/untagged-aa4c309bf327368572f0
* [x] Create version update PR: https://github.com/blue-oil/blueoil/pull/278
* [x] Create release branch. `r0.7`
* [x] merge PR. update `r0.7` branch location to master.
* [x] Publish release note on github.
* [x] Check https://github.com/LeapMind/delta-core will auto release.
* [x] Post in blueoil slack
* [x] Send mail to internal.
