### ISSUE TITLE
Ultra96v2 Support

### ISSUE THREAD

**Issue by hadusam** [blue-oil/blueoil#599]
Support for Ultra96v2

## Steps
- [ ] Create Ultra96v2 Image with Ubuntu 18.04
- [ ] Update DLK for aarch64 + fpga (Ultra96v2)
- [ ] Add CI for Ultra96v2

## Create Ultra96v2 Image with Ubuntu 18.04
We need the following files to create a SD card image
* boot-loader
  * u-boot files
* OS and kernel
  * raw_partition.img(rootfs)
  * zImage
  * kernel_modules.tar.gz
  * udmabuf.ko
* FPGA
  * preloader-mkpimage.bin
  * soc_system.dtb
  * soc_system.rbf
### Tasks
- [ ] Build rootfs #560 
- [ ] Build zImage and kernel modules
- [ ] Build FPGA files and boot-loader for Ultra96v2
- [ ] Create SD card image with all files
- [ ] Upload new image for public and Update Documents for Ultra96v2

### Concerns
Where should we put the generated above files?
Current binary files for DE10-Nano is on this GitHub repository, but it is not a good method to manage binary files.

**Comment by hadusam** [comment]
@tk26eng 
I created an issue for Ultra96v2 support, please check it. Let's discuss this here. 👍
